[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Texas", email = "texas@wildwestverse.com"}]
dynamic = ["version", "description"]
